
ai_description = (
"The purpose of an AI engineer position is to design, develop, and implement artificial intelligence solutions to address complex problems "
"and enhance processes within an organization. This role aims to leverage advanced algorithms, machine learning, and deep learning techniques to create intelligent systems that can analyze data, "
"make predictions, and automate tasks. Ultimately, the AI engineer contributes to technological innovation, "
"improves efficiency, and helps the organization stay competitive by harnessing the power of artificial intelligence "
"in various applications, such as data analysis, image recognition, natural language processing, and more."
"Requirements:Design and optimize machine learning algorithms for specific applications. "
"Manage and preprocess large datasets to extract relevant features for training AI models"
"Train machine learning models and evaluate their performance through testing"
"Use programming languages (e.g., Python, Java) for AI development"
"Apply expertise in deep learning frameworks like TensorFlow or PyTorch to build and implement neural networks"
"Work closely with cross-functional teams, including data scientists, software engineers, and domain experts"
" Analyze complex problems and propose innovative AI solutions to address business challenges"
"Stay updated on the latest advancements in AI and integrate new technologies into existing systems"
"Ensure AI applications comply with ethical standards and legal regulations"
" Prepare comprehensive documentation for algorithms, models, and processes"
"Engage in ongoing learning to stay abreast of emerging technologies and industry trends"
"Assist in deploying AI models into production environments, ensuring scalability and efficiency."

)

cyber_security_description = (
"Job ObjectiveProtecting our organization's information systems from cyber threats, ensuring confidentiality, integrity, and availability of data. This role involves monitoring security systems, responding to incidents, and implementing effective security measures."
"Responsibilities"
"Work hand in hand with the technology strategy teams to better understand business needs that would require developing network and infrastructure solutions."
"Develop, implement, and test multiple infrastructure components (Firewall, WAF, servers, routers, switches, etc.) according to detailed design specifications."
"Work closely with application development teams to forecast infrastructure needs and capacity planning."
"Contribute to the development of business continuity plan, disaster recovery plan, and risk items."
"Configure routing and switching equipment, IP voice services and firewalls."
"Support and administer firewall environments in line with Cybersecurity policy and procedures."
"Monitor network performance and integrity"
"Create, oversee, and test security measures (e.g. access authentication and disaster recovery)"
"Communicate with users when needed"
"Maintain complete technical documentation"
"Suggest improvements to network performance, capacity, and scalability"
"Monitor network traffic for unusual activity and potential threats."
"Conduct regular security assessments and audits to identify vulnerabilities."
"Develop and implement security policies, standards, and procedures."
"Respond to security incidents and breaches, coordinating investigations and remediation efforts."
"Collaborate with IT teams to ensure secure system configurations and updates."
"Provide training and awareness programs for employees on security best practices."
"Stay updated on the latest security trends, threats, and technology solutions."
"Assist in compliance with regulatory requirements and industry standards."
"Familiarity with firewalls, intrusion detection systems, and encryption technologies."
"Other Related Assignments"
"Complete duties as requested by direct line manager"
"Required Education"
"Bachelor's degree in computer science, Information Technology, Cyber Security, or a related field."
"Knowledge of security frameworks (e.g., NIST, ISO 27001) and compliance regulations (e.g., GDPR, HIPAA)."
"Proven experience in cyber security roles, with a strong understanding of security protocols and tools."
"Relevant certifications (e.g., CISSP, CISM, CEH) are a plus"
"Required Years of Experience"
"Minimum of 0-4 years of experience in a similar role or function"
"Soft Skills"
"Communication Skills"
"Teamwork and Collaboration"
"Problem-Solving"
"Strong analytical")



cloud_engineering_description = (
"We are seeking a DevOps Cloud Engineer to join our Technology Unit in Dammam, Saudi Arabia. This role is ideal for a proactive professional with expertise in cloud platforms, automation, and CI CD pipelines who thrives in fast-paced, innovative environments."
"You will play a critical role in designing and maintaining secure, scalable infrastructure to support both enterprise applications and advanced AI/ML workloads, working closely with cross-functional teams across development, QA, operations, and data science."
"Key Responsibilities"
"Design, build, and maintain scalable and secure cloud infrastructure on AWS, Azure, or GCP."
"Develop and optimize CI CD pipelines with integrated testing, monitoring, and security."
"Architect and support machine learning workflows, including generative AI workloads."
"Implement and manage containerized environments using Docker and Kubernetes."
"Automate infrastructure and operational tasks using Terraform, Ansible, Python, or Bash."
"Establish and manage observability tools (Prometheus, Grafana, ELK, CloudWatch, Datadog)."
"Ensure compliance with industry standards and security best practices."
"Collaborate with cross-functional teams to support agile development and deployment practices."
)

software_engineering_description= (
"Experience: 5+ years Responsibilities:"
"Work as a full-stack developer handling Java backend and React front-end development."
"Build responsive and user-friendly front-end interfaces using ReactJS."
"Develop scalable, high-performance backend APIs with Java and Spring Boot."
"Ensure smooth integration between front-end and backend services."
"Participate in code reviews, Agile sprint planning, and collaborative development activities."
"Troubleshoot, debug, and optimize applications for maximum efficiency."
"Skills & Qualifications:"
"Strong expertise in Java, Spring Boot, Hibernate."
"Proficient in ReactJS, JavaScript/TypeScript, Redux."
"Experience in developing RESTful APIs and integrating with front-end applications."
"Familiarity with DevOps practices and cloud platforms is a plus."
"Excellent problem-solving, communication, and teamwork skills."
)
